### PR TITLE
Differential Flame Graphs

### PR DESCRIPTION
**Pull request by Arkoniak**
As it was proposed #5 it would be nice to have differential flame graphs as an additional graph. Here it's implementation. Most of the new things are described in the `README.md`, one can build `baseline` profile and then compare it to new implementations of the code.

As a side effect of this implementation, I've restructured code a little, hope that's ok.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Wow, this is amazing, thank you!

@timholy, have you seen this?

I guess one question is whether we should move some of the processing logic into FlameGraphs.jl itself?

**Comment by timholy** [comment]
I saw https://github.com/timholy/FlameGraphs.jl/issues/7 but had a grant due today so hadn't gotten to it.

Awesome work, @Arkoniak. I'd strongly recommend moving most of this to FlameGraphs itself. ProfileVega is just one of what are now 4 front ends for FlameGraphs (ProfileView, Juno, and ProfileSVG being the others).

**Comment by davidanthoff** [comment]
Yes on moving the code. Once I integrate this into VS Code we'll have another front end (that won't rely on this package here), we could also do an Electron based front-end, which would be yet another one.

**Comment by Arkoniak** [comment]
Thank you very much :-)
Yes, I will move it to FlameGraphs, no problems.

**Pull request merged**
